# Generated by Django 6.1 on 2026-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockrecord_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='reason',
            field=models.CharField(choices=[('INITIAL', '首次入库'), ('PURCHASE', '采购入库'), ('RETURN', '归还入库'), ('TRANSFER_IN', '调拨入库'), ('BORROW', '借出'), ('SCRAP', '报废'), ('DAMAGE', '损坏'), ('TRANSFER_OUT', '调拨'), ('CHECK', '盘点减少')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='type',
            field=models.CharField(choices=[('IN', '增加库存'), ('OUT', '减少库存')], max_length=20),
        ),
    ]
