# Generated by Django 6.1 on 2026-09-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_last_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_modified_by',
        ),
    ]
