# Generated by Django 6.1 on 2026-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_item_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_location_image',
            field=models.ImageField(blank=True, null=True, upload_to='current_location/'),
        ),
    ]
