# Generated by Django 6.1 on 2026-09-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_current_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='失效时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='valid_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='有效期(月)'),
        ),
    ]
