# Generated by Django 6.1 on 2026-09-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_expiry_date_item_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
