# Generated by Django 6.1 on 2026-09-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_last_modified_by_item_last_modified_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiration_date',
        ),
    ]
