# Generated by Django 6.1 on 2026-09-16 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='设备编号')),
                ('status', models.CharField(choices=[('AVAILABLE', '可用'), ('BORROWED', '借出'), ('DAMAGED', '损坏'), ('LOST', '丢失')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.item')),
            ],
        ),
    ]
