# Generated by Django 6.1 on 2026-09-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.asset'),
        ),
    ]
