# Generated by Django 6.1 on 2026-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockrecord_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_serialized',
            field=models.BooleanField(default=False, verbose_name='是否需要设备编号'),
        ),
    ]
