# Generated by Django 6.1 on 2026-09-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_item_is_serialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_serialized',
            field=models.BooleanField(default=False, verbose_name='是否单件管理'),
        ),
    ]
